name: Create Tag and Release

on:
  pull_request:
    types: [closed]

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main' && startsWith(github.head_ref, 'release/')
    
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Extract version from branch name
        run: |
          VERSION_NO=$(echo "${{ github.event.pull_request.head.ref }}" | cut -d/ -f2)
          echo "RELEASE_VERSION=${VERSION_NO}" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          release_name: v${{ env.RELEASE_VERSION }}
          body: ${{ github.event.pull_request.body }}
          draft: true
          prerelease: false
